### ISSUE TITLE
Add ability to remove messages from a QDB queue

### ISSUE THREAD

**Issue by ke4** [qdb-io/qdb-server#7]
Our team found QDB as a useful RabbitMQ related tool. Thanks for sharing it with the world. ;)
The only thing we miss is the ability to delete a message or messages from a given QDB queue.
It would help us manage the size of the storage. Also, we could remove messages from a queue what we are not interested in anymore.
I think, it would be a useful feature if you would have time to implement it.
Many thanks,

Karel

**Comment by davidtinker** [comment]
Tx. QDB automatically deletes the oldest messages when a queue reaches its configured maximum size. This is done very efficiently by deleting a segment file on disk. QBD's message buffers are fast because they are append only and it would be hard to add editing support. You could keep track of message IDs you don't care about somewhere else and skip them when encountered?

**Comment by ke4** [comment]
Thanks for your quick and useful answer. We will discuss it further with our team and we might be able to use QDB for our purposes.
Have a great day!
Karel
